### Задание 1

Смоделируем 60-кратное подбрасывание игральной кости с помощью функции random.randint пакета numpy, то есть n = 60.

Событие A будем считать выпадение числа 3 и найдем его относительную частоту.

In [1]:
import numpy as np

In [15]:
np.random.seed(1)
n = 60
a = np.random.randint(1, 7, n)
a

array([6, 4, 5, 1, 2, 4, 6, 1, 1, 2, 5, 6, 5, 2, 3, 5, 6, 3, 5, 4, 5, 3,
       5, 6, 3, 5, 2, 2, 1, 6, 2, 2, 6, 2, 2, 1, 5, 2, 1, 1, 6, 4, 3, 2,
       1, 4, 6, 2, 2, 4, 5, 1, 2, 4, 5, 3, 5, 1, 6, 4])

In [16]:
m = a[a == 3].size
m

6

In [17]:
W = m / n
W

0.1

### Задание 2

Смоделируем ситуацию, когда бросают две игральные кости одновременно. 

При этом будем находить частоту случайного события B, при котором на одной кости выпало 1, а на другой - 2.

Проведем для этого 360 испытаний. Сразу зададим число n:

In [18]:
n = 360

In [19]:
c = np.random.randint(1, 7, n)
d = np.random.randint(1, 7, n)

In [20]:
c

array([2, 3, 1, 5, 2, 3, 3, 2, 1, 2, 4, 6, 5, 4, 6, 2, 4, 1, 1, 3, 3, 2,
       4, 5, 3, 1, 1, 2, 2, 6, 4, 1, 1, 6, 6, 5, 6, 3, 5, 4, 6, 4, 6, 1,
       4, 5, 4, 5, 5, 6, 5, 2, 1, 5, 3, 1, 6, 3, 5, 2, 2, 1, 3, 5, 5, 1,
       5, 2, 5, 2, 1, 3, 4, 2, 3, 5, 5, 3, 3, 1, 2, 3, 3, 1, 6, 2, 3, 5,
       1, 6, 6, 2, 3, 2, 6, 5, 3, 1, 6, 1, 2, 6, 1, 2, 4, 2, 2, 6, 5, 5,
       4, 6, 1, 4, 1, 4, 2, 3, 6, 6, 5, 6, 1, 6, 1, 6, 4, 2, 2, 6, 1, 6,
       1, 5, 3, 6, 4, 5, 3, 1, 6, 4, 4, 6, 6, 2, 3, 5, 4, 1, 1, 6, 5, 3,
       5, 3, 1, 6, 4, 1, 1, 5, 6, 3, 2, 1, 5, 4, 1, 2, 3, 5, 5, 4, 4, 4,
       4, 3, 4, 4, 6, 5, 4, 3, 5, 5, 1, 4, 4, 1, 4, 6, 6, 2, 1, 3, 3, 3,
       1, 3, 2, 5, 1, 5, 5, 2, 4, 2, 5, 2, 3, 6, 2, 1, 1, 3, 5, 2, 1, 1,
       4, 2, 1, 5, 4, 3, 4, 5, 6, 5, 4, 1, 1, 1, 5, 6, 2, 6, 5, 2, 3, 6,
       3, 6, 5, 6, 4, 5, 5, 1, 4, 3, 5, 6, 4, 5, 3, 4, 1, 6, 6, 3, 2, 4,
       3, 1, 6, 2, 5, 2, 4, 4, 2, 3, 1, 3, 5, 1, 3, 5, 4, 5, 4, 1, 6, 6,
       5, 3, 3, 5, 2, 3, 6, 2, 2, 2, 1, 6, 6, 5, 5,

In [21]:
d

array([4, 4, 1, 4, 2, 3, 1, 2, 5, 3, 4, 5, 6, 5, 3, 2, 3, 6, 1, 6, 4, 6,
       4, 3, 1, 1, 1, 1, 3, 5, 1, 5, 2, 3, 2, 3, 5, 2, 4, 6, 2, 6, 2, 3,
       5, 2, 1, 3, 6, 2, 3, 1, 1, 6, 4, 5, 2, 6, 1, 5, 1, 4, 3, 5, 4, 3,
       5, 3, 5, 1, 1, 6, 5, 3, 3, 5, 3, 4, 6, 1, 1, 5, 4, 5, 4, 4, 5, 1,
       6, 4, 6, 2, 5, 5, 4, 3, 3, 3, 3, 3, 1, 3, 2, 6, 3, 4, 6, 1, 1, 6,
       6, 6, 2, 2, 4, 4, 6, 4, 2, 4, 4, 4, 2, 4, 1, 5, 6, 1, 6, 6, 3, 5,
       5, 3, 1, 4, 6, 3, 5, 6, 1, 5, 6, 3, 4, 5, 3, 5, 2, 4, 5, 4, 1, 4,
       1, 5, 4, 1, 6, 4, 2, 5, 5, 6, 3, 6, 6, 3, 5, 3, 2, 3, 4, 2, 6, 6,
       4, 4, 1, 5, 4, 4, 6, 4, 4, 1, 3, 4, 6, 2, 6, 4, 3, 6, 4, 3, 6, 3,
       1, 5, 1, 2, 4, 1, 1, 1, 2, 3, 5, 5, 3, 1, 2, 1, 1, 6, 3, 6, 5, 4,
       1, 3, 2, 4, 4, 2, 5, 5, 5, 6, 1, 2, 1, 2, 3, 3, 5, 6, 6, 3, 5, 6,
       1, 6, 3, 6, 5, 5, 2, 2, 2, 2, 6, 5, 6, 4, 5, 2, 2, 6, 2, 3, 5, 4,
       3, 4, 4, 3, 4, 1, 3, 1, 2, 6, 1, 6, 1, 4, 5, 1, 1, 6, 1, 1, 2, 1,
       6, 2, 4, 4, 5, 6, 1, 2, 6, 1, 4, 3, 2, 2, 1,

In [34]:
e = c[(c==1) & (d==2)]
e

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [35]:
m = len(e)
m


11

In [36]:
W = m / n
W

0.030555555555555555