In [5]:
import numpy as np

### Выбор данных

In [6]:
a = np.random.randint(0, 20, 10)
a

array([19, 15, 14,  3, 15, 12,  1, 10, 13,  2])

In [7]:
a[a > 10]

array([19, 15, 14, 15, 12, 13])

In [8]:
a[(a > 10) & (a % 2 == 0)]

array([14, 12])

In [9]:
a[(a > 10) | (a % 3 == 0)]

array([19, 15, 14,  3, 15, 12, 13])

numpy.where - первый вариант применения

In [10]:
a

array([19, 15, 14,  3, 15, 12,  1, 10, 13,  2])

In [11]:
np.where(a > 10) # Возращает индексы

(array([0, 1, 2, 4, 5, 8]),)

In [12]:
a[np.where(a > 10)]

array([19, 15, 14, 15, 12, 13])

numpy.where - второй вариант применения

In [21]:
a = [1, 4, 7]
b = [9, 78, 5]

In [22]:
# Если True - то берем из массива а, иначе из b
np.where([True, False, True], a, b)

array([ 1, 78,  7])

### Сортировка

In [24]:
a = np.array([[1, 3, 9, 9], [5, 0, 1, 5], [2, 7, 3, 5]])

In [27]:
a[[0, 2, 1], :]

array([[1, 3, 9, 9],
       [2, 7, 3, 5],
       [5, 0, 1, 5]])

In [29]:
a.argsort(axis=0)

array([[0, 1, 1, 1],
       [2, 0, 2, 2],
       [1, 2, 0, 0]])

In [30]:
a[:, 0].argsort()

array([0, 2, 1])

In [31]:
a[a[:, 0].argsort(), :]

array([[1, 3, 9, 9],
       [2, 7, 3, 5],
       [5, 0, 1, 5]])

### Случайное перемешивание массивов

Одномерные массивы

In [33]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.random.shuffle(a)
a

array([3, 6, 1, 7, 5, 9, 4, 2, 0, 8])

Двумерные массивы

In [80]:
a = np.arange(12).reshape(4, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [95]:
np.random.shuffle(a)
a

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [ 3,  4,  5]])

### Математические действия с массивами

Применение математических функций ко всему массиву

In [49]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
np.log(a) # Логарифм по основанию e

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [52]:
np.exp(a)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [53]:
a.sum()

np.int64(21)

In [54]:
a.sum(axis=0)

array([5, 7, 9])

In [55]:
a.sum(axis=1)

array([ 6, 15])

In [56]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
10 + a

array([[11, 12, 13],
       [14, 15, 16]])

Поэлементное (не матричное) умножение

In [97]:
a = np.arange(12).reshape(3, -1)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [62]:
b = np.arange(12, 24).reshape(-1, 4)
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [63]:
a * b

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

#### Broadcasting (на примере сложения)

In [64]:
a = np.array([[2, 5], [3, 4], [6, 1]])
a

array([[2, 5],
       [3, 4],
       [6, 1]])

1 случай - совпадает только число столбцов

In [65]:
b = np.array([1, 2])
b

array([1, 2])

In [66]:
a + b

array([[3, 7],
       [4, 6],
       [7, 3]])

2 случай - совпадает только число строк

In [67]:
c = np.array([[1], [2], [3]])
c

array([[1],
       [2],
       [3]])

In [68]:
a + c

array([[3, 6],
       [5, 6],
       [9, 4]])

### Статистические функции

In [69]:
a = np.random.randint(0, 12, (3, 4))
a

array([[ 0,  6,  6,  7],
       [ 2,  4,  0,  4],
       [ 3, 11,  6,  5]])

In [70]:
a.min()

np.int64(0)

In [71]:
a.min(axis=0)

array([0, 4, 0, 4])

In [72]:
a.max(axis=1)

array([ 7,  4, 11])

In [73]:
a.mean(axis=0)

array([1.66666667, 7.        , 4.        , 5.33333333])

In [74]:
a.std(axis=0)

array([1.24721913, 2.94392029, 2.82842712, 1.24721913])

### Запись и чтение массива из файла

In [75]:
np.save('a.npy', a)

In [76]:
b = np.load('a.npy')
b

array([[ 0,  6,  6,  7],
       [ 2,  4,  0,  4],
       [ 3, 11,  6,  5]])