In [44]:
import numpy as np

### Выбор данных

In [45]:
a = np.random.randint(0, 20, 10)
a

array([13, 16,  6,  8,  5, 15,  9,  2, 11, 13])

In [46]:
a[a > 10]

array([13, 16, 15, 11, 13])

In [47]:
a[(a > 10) & (a % 2 == 0)]

array([16])

In [48]:
a[(a > 10) | (a % 3 == 0)]

array([13, 16,  6, 15,  9, 11, 13])

numpy.where - первый вариант применения

In [49]:
a

array([13, 16,  6,  8,  5, 15,  9,  2, 11, 13])

In [50]:
np.where(a > 10) # Возращает индексы

(array([0, 1, 5, 8, 9]),)

In [51]:
a[np.where(a > 10)]

array([13, 16, 15, 11, 13])

numpy.where - второй вариант применения

In [52]:
a = [1, 4, 7]
b = [9, 78, 5]

In [53]:
# Если True - то берем из массива а, иначе из b
np.where([True, False, True], a, b)

array([ 1, 78,  7])

### Сортировка

In [88]:
a = np.array([[1, 3, 9, 9], [5, 0, 1, 5], [2, 7, 3, 5]])
a

array([[1, 3, 9, 9],
       [5, 0, 1, 5],
       [2, 7, 3, 5]])

In [55]:
a[[0, 2, 1], :]

array([[1, 3, 9, 9],
       [2, 7, 3, 5],
       [5, 0, 1, 5]])

In [56]:
a.argsort(axis=0)

array([[0, 1, 1, 1],
       [2, 0, 2, 2],
       [1, 2, 0, 0]])

In [57]:
a[:, 0].argsort()

array([0, 2, 1])

In [58]:
a[a[:, 0].argsort(), :]

array([[1, 3, 9, 9],
       [2, 7, 3, 5],
       [5, 0, 1, 5]])

### Случайное перемешивание массивов

Одномерные массивы

In [59]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
np.random.shuffle(a)
a

array([6, 2, 1, 9, 8, 4, 5, 0, 3, 7])

Двумерные массивы

In [61]:
a = np.arange(12).reshape(4, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [62]:
np.random.shuffle(a)
a

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [ 3,  4,  5],
       [ 0,  1,  2]])

### Математические действия с массивами

Применение математических функций ко всему массиву

In [63]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
np.log(a) # Логарифм по основанию e

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [65]:
np.exp(a)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [66]:
a.sum()

np.int64(21)

In [67]:
a.sum(axis=0)

array([5, 7, 9])

In [68]:
a.sum(axis=1)

array([ 6, 15])

In [69]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
10 + a

array([[11, 12, 13],
       [14, 15, 16]])

Поэлементное (не матричное) умножение

In [71]:
a = np.arange(12).reshape(3, -1)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [72]:
b = np.arange(12, 24).reshape(-1, 4)
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [73]:
a * b

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

#### Broadcasting (на примере сложения)

In [74]:
a = np.array([[2, 5], [3, 4], [6, 1]])
a

array([[2, 5],
       [3, 4],
       [6, 1]])

1 случай - совпадает только число столбцов

In [75]:
b = np.array([1, 2])
b

array([1, 2])

In [76]:
a + b

array([[3, 7],
       [4, 6],
       [7, 3]])

2 случай - совпадает только число строк

In [77]:
c = np.array([[1], [2], [3]])
c

array([[1],
       [2],
       [3]])

In [78]:
a + c

array([[3, 6],
       [5, 6],
       [9, 4]])

### Статистические функции

In [79]:
a = np.random.randint(0, 12, (3, 4))
a

array([[10, 10,  2,  0],
       [ 2,  2,  3, 11],
       [ 2, 11,  1, 11]])

In [80]:
a.min()

np.int64(0)

In [81]:
a.min(axis=0)

array([2, 2, 1, 0])

In [82]:
a.max(axis=1)

array([10, 11, 11])

In [83]:
a.mean(axis=0)

array([4.66666667, 7.66666667, 2.        , 7.33333333])

In [84]:
a.std(axis=0)

array([3.77123617, 4.02768199, 0.81649658, 5.18544973])

### Запись и чтение массива из файла

In [85]:
np.save('a.npy', a)

In [86]:
b = np.load('a.npy')
b

array([[10, 10,  2,  0],
       [ 2,  2,  3, 11],
       [ 2, 11,  1, 11]])