In [1]:
import numpy as np

### Автоматическое создание массивов

In [2]:
a = np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
a = np.ones((5, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(2, 10, 3)

array([2, 5, 8])

In [7]:
np.arange(10, 2, -1)

array([10,  9,  8,  7,  6,  5,  4,  3])

In [8]:
np.arange(10, 2, -0.1)

array([10. ,  9.9,  9.8,  9.7,  9.6,  9.5,  9.4,  9.3,  9.2,  9.1,  9. ,
        8.9,  8.8,  8.7,  8.6,  8.5,  8.4,  8.3,  8.2,  8.1,  8. ,  7.9,
        7.8,  7.7,  7.6,  7.5,  7.4,  7.3,  7.2,  7.1,  7. ,  6.9,  6.8,
        6.7,  6.6,  6.5,  6.4,  6.3,  6.2,  6.1,  6. ,  5.9,  5.8,  5.7,
        5.6,  5.5,  5.4,  5.3,  5.2,  5.1,  5. ,  4.9,  4.8,  4.7,  4.6,
        4.5,  4.4,  4.3,  4.2,  4.1,  4. ,  3.9,  3.8,  3.7,  3.6,  3.5,
        3.4,  3.3,  3.2,  3.1,  3. ,  2.9,  2.8,  2.7,  2.6,  2.5,  2.4,
        2.3,  2.2,  2.1])

In [9]:
np.linspace(0, 9.9, 100) # вместо шага пишем число элементов

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [10]:
np.logspace(0, 4, 5, dtype=int) # степени числа 10

array([    1,    10,   100,  1000, 10000])

#### Генерация случайных чисел
np.random.sample - случайные числа с равномерным распределением в промежутке [0.0, 1.0]

In [11]:
np.random.sample()

0.8066192036073474

In [12]:
np.random.sample(3)

array([0.44862472, 0.83047065, 0.04984081])

In [13]:
np.random.sample((2, 3))

array([[0.38109154, 0.11973251, 0.70592672],
       [0.98090813, 0.49315383, 0.02941467]])

In [14]:
np.random.sample((48, 64, 3))

array([[[0.12094418, 0.9856405 , 0.35554205],
        [0.91496116, 0.70162732, 0.14784247],
        [0.06904174, 0.9683994 , 0.95006365],
        ...,
        [0.09962771, 0.18539998, 0.33586363],
        [0.28458186, 0.22493713, 0.14750213],
        [0.63935751, 0.4497199 , 0.64042863]],

       [[0.61629142, 0.32174032, 0.42314524],
        [0.28810074, 0.92315373, 0.2838401 ],
        [0.19402168, 0.83271707, 0.46737976],
        ...,
        [0.69496408, 0.64516133, 0.71873264],
        [0.8156251 , 0.4757646 , 0.69332814],
        [0.51797783, 0.66296157, 0.60779004]],

       [[0.24754278, 0.9704215 , 0.1885321 ],
        [0.94296293, 0.6838008 , 0.41224157],
        [0.58328932, 0.16368359, 0.70391648],
        ...,
        [0.04513734, 0.19809178, 0.62866381],
        [0.52893866, 0.42992608, 0.68874216],
        [0.99587465, 0.00893274, 0.84072289]],

       ...,

       [[0.7461589 , 0.62668419, 0.7849492 ],
        [0.50374477, 0.65231333, 0.20058106],
        [0.99318052, 0

numpy.random.randn - случайные числа с нормальным распределением 
(среднее значение = 0, среднеквадратичное отклонение = 1)

In [15]:
np.random.randn(10)

array([ 0.41306402,  0.21933536,  0.87186886,  0.03956234, -0.39971139,
       -0.46860632,  0.33553194,  0.83177944, -0.20186421, -0.24748235])

In [16]:
np.random.randn(3, 4)

array([[ 1.32254039, -0.06086282,  0.40204865,  0.98206517],
       [-0.35389551,  0.18309716, -0.51885372, -1.07836228],
       [-0.31605373, -0.36975566, -1.35521002,  0.64927881]])

numpy.random.randint - массив из целых чисел

In [17]:
np.random.randint(0, 100, 10)

array([93, 21, 92, 94, 13, 54,  0, 40, 77, 93])

In [18]:
np.random.randint(0, 10, (3, 4))

array([[3, 3, 2, 8],
       [5, 1, 2, 2],
       [4, 9, 3, 5]])

numpy.random.choice - случайный выбор элементов из массива

In [19]:
b = np.array([1, 2, 5, 4, 6, 7, 3, 2])

In [20]:
np.random.choice(b)

np.int64(1)

In [21]:
np.random.choice(b, 3)

array([1, 3, 1])

numpy.random.seed - инициализация генератора случайных чисел


Может использоваться для последующей воспроизводимости (будут генерироваться те же числа, если установить одинаковый seed)

In [22]:
np.random.seed(42)

In [23]:
np.random.randint(0, 10, 3)

array([6, 3, 7])

### Изменение формы массива

In [24]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
a.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
np.reshape(a, (3, -1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
np.reshape(a, (-1, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
a.resize(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
a = a.flatten()
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Соединение массивов

In [32]:
a = np.zeros((2, 3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
b = np.ones((2, 3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

#### Соединение строк (вертикально)

In [34]:
v = np.vstack((a, b))
v

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
a.shape, b.shape, v.shape

((2, 3), (2, 3), (4, 3))

In [36]:
np.concatenate((a, b), axis=0)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### Соединение столбцов (горизонтально)

In [37]:
h = np.hstack((a, b))
h

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [38]:
a.shape, b.shape, h.shape

((2, 3), (2, 3), (2, 6))

In [39]:
np.concatenate((a, b), axis=1)

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

#### Соединение в глубину (в третьем измерении)

In [40]:
d = np.dstack([a, b])
d

array([[[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]]])