In [91]:
import numpy as np

### Автоматическое создание массивов

In [2]:
a = np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
a = np.ones((5, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(2, 10, 3)

array([2, 5, 8])

In [7]:
np.arange(10, 2, -1)

array([10,  9,  8,  7,  6,  5,  4,  3])

In [8]:
np.arange(10, 2, -0.1)

array([10. ,  9.9,  9.8,  9.7,  9.6,  9.5,  9.4,  9.3,  9.2,  9.1,  9. ,
        8.9,  8.8,  8.7,  8.6,  8.5,  8.4,  8.3,  8.2,  8.1,  8. ,  7.9,
        7.8,  7.7,  7.6,  7.5,  7.4,  7.3,  7.2,  7.1,  7. ,  6.9,  6.8,
        6.7,  6.6,  6.5,  6.4,  6.3,  6.2,  6.1,  6. ,  5.9,  5.8,  5.7,
        5.6,  5.5,  5.4,  5.3,  5.2,  5.1,  5. ,  4.9,  4.8,  4.7,  4.6,
        4.5,  4.4,  4.3,  4.2,  4.1,  4. ,  3.9,  3.8,  3.7,  3.6,  3.5,
        3.4,  3.3,  3.2,  3.1,  3. ,  2.9,  2.8,  2.7,  2.6,  2.5,  2.4,
        2.3,  2.2,  2.1])

In [14]:
np.linspace(0, 9.9, 100) # вместо шага пишем число элементов

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [93]:
np.logspace(0, 3, 4) # степени числа 10

array([   1.,   10.,  100., 1000.])

#### Генерация случайных чисел
np.random.sample - случайные числа с равномерным распределением в промежутке [0.0, 1.0]

In [29]:
np.random.sample()

0.338588505548296

In [35]:
np.random.sample(3)

array([0.39984936, 0.72548819, 0.37433456])

In [36]:
np.random.sample((2, 3))

array([[0.8545026 , 0.81920343, 0.65087839],
       [0.73992966, 0.99800718, 0.88134696]])

In [37]:
np.random.sample((48, 64, 3))

array([[[0.61246383, 0.83298104, 0.36989948],
        [0.73881215, 0.81960639, 0.10966666],
        [0.4404818 , 0.81030918, 0.74284225],
        ...,
        [0.72125426, 0.11900133, 0.70084101],
        [0.59793227, 0.62079222, 0.02517962],
        [0.10783511, 0.17856728, 0.86733539]],

       [[0.5792715 , 0.44333896, 0.95589477],
        [0.26619382, 0.62361157, 0.51928582],
        [0.43904265, 0.64526901, 0.90849166],
        ...,
        [0.09048733, 0.92825879, 0.46535291],
        [0.85185824, 0.61342012, 0.40633085],
        [0.27305643, 0.28495756, 0.96506993]],

       [[0.49810069, 0.33924183, 0.82508188],
        [0.69158012, 0.90111551, 0.5053364 ],
        [0.21183116, 0.16059568, 0.49279461],
        ...,
        [0.06007839, 0.52974343, 0.04171405],
        [0.93298707, 0.01500424, 0.6199989 ],
        [0.66261693, 0.75269548, 0.62686122]],

       ...,

       [[0.21348191, 0.16746674, 0.54122235],
        [0.42746998, 0.97800985, 0.73970279],
        [0.56628413, 0

numpy.random.randn - случайные числа с нормальным распределением 
(среднее значение = 0, среднеквадратичное отклонение = 1)

In [38]:
np.random.randn(10)

array([-1.41142905,  0.63826086,  1.51497084,  0.23948824, -0.66329698,
       -0.18613202,  0.02173744,  0.1475566 , -0.16563322,  0.16590693])

In [40]:
np.random.randn(3, 4)

array([[ 0.40799347, -0.1626149 ,  1.29359691, -0.55819609],
       [ 1.24313527, -0.30150863, -1.00527833,  0.15185985],
       [-1.88714262, -1.05735154,  0.7506751 , -0.69413981]])

numpy.random.randint - массив из целых чисел

In [41]:
np.random.randint(0, 100, 10)

array([ 5, 59, 97, 32, 48, 37, 64, 75, 31, 40])

In [43]:
np.random.randint(0, 10, (3, 4))

array([[3, 2, 3, 7],
       [0, 2, 4, 5],
       [6, 0, 7, 0]])

numpy.random.choice - случайный выбор элементов из массива

In [44]:
b = np.array([1, 2, 5, 4, 6, 7, 3, 2])

In [47]:
np.random.choice(b)

np.int64(1)

In [50]:
np.random.choice(b, 3)

array([7, 5, 2])

numpy.random.seed - инициализация генератора случайных чисел


Может использоваться для последующей воспроизводимости (будут генерироваться те же числа, если установить одинаковый seed)

In [99]:
np.random.seed(42)

In [110]:
np.random.randint(0, 10, 3)

array([8, 2, 4])

### Изменение формы массива

In [65]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [66]:
a.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [70]:
np.reshape(a, (3, -1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [71]:
np.reshape(a, (-1, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [72]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [74]:
a.resize(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [75]:
a = a.flatten()
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Соединение массивов

In [76]:
a = np.zeros((2, 3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [77]:
b = np.ones((2, 3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

#### Соединение строк (вертикально)

In [79]:
v = np.vstack((a, b))
v

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [80]:
a.shape, b.shape, v.shape

((2, 3), (2, 3), (4, 3))

In [81]:
np.concatenate((a, b), axis=0)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### Соединение столбцов (горизонтально)

In [83]:
h = np.hstack((a, b))
h

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [85]:
a.shape, b.shape, h.shape

((2, 3), (2, 3), (2, 6))

In [86]:
np.concatenate((a, b), axis=1)

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

#### Соединение в глубину (в третьем измерении)

In [90]:
d = np.dstack([a, b])
d

array([[[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]]])