# Операция с векторами

In [1]:
import numpy as np

In [2]:
a = np.array([0, 1, 8, 3, 4])

In [3]:
b = np.array([5, 6, 7, 8, 9])

In [4]:
a.size, b.size

(5, 5)

### Сложение вектров

In [5]:
c = a + b
c

array([ 5,  7, 15, 11, 13])

In [6]:
c = np.add(a, b)
c

array([ 5,  7, 15, 11, 13])

### Вычитание векторов

In [7]:
d = a - b
d

array([-5, -5,  1, -5, -5])

In [8]:
d = np.subtract(a, b)
d

array([-5, -5,  1, -5, -5])

### Умножение вектора на скаляр

In [9]:
c = a * 2
c

array([ 0,  2, 16,  6,  8])

In [10]:
c = -10 * a
c

array([  0, -10, -80, -30, -40])

In [11]:
c = 0.6 * a
c

array([0. , 0.6, 4.8, 1.8, 2.4])

In [12]:
a.dot(-10)

array([  0, -10, -80, -30, -40])

In [13]:
np.dot(-10, a)

array([  0, -10, -80, -30, -40])

In [14]:
np.multiply(-10, a)

array([  0, -10, -80, -30, -40])

### Скалярное произведение векторов

In [15]:
a = np.array([0, 1, 8, 3, 4])
b = np.array([5, 6, 7, 8, 9])

In [16]:
sp = a[0] * b[0] + a[1] * b[1] + a[2] * b[2] + a[3] * b[3] + a[4] * b[4] 
sp

np.int64(122)

In [17]:
a @ b

np.int64(122)

In [27]:
sp = np.dot(a, b)
sp

np.int64(122)

# Операции с матрицами

In [19]:
A = np.array([[0, 1], [2, 3], [4, 5]])

In [20]:
B = np.array([[6, 7], [8, 9], [6, 3]])

### Сложение матриц

In [21]:
C = A + B
C

array([[ 6,  8],
       [10, 12],
       [10,  8]])

In [22]:
C = np.add(A, B)
C

array([[ 6,  8],
       [10, 12],
       [10,  8]])

### Вычитание матриц

In [23]:
D = A - B
D

array([[-6, -6],
       [-6, -6],
       [-2,  2]])

In [24]:
D = np.subtract(A, B)
D

array([[-6, -6],
       [-6, -6],
       [-2,  2]])

### Умножение матрицы на скаляр

In [25]:
V = A * 3
V

array([[ 0,  3],
       [ 6,  9],
       [12, 15]])

In [26]:
np.dot(3, B)

array([[18, 21],
       [24, 27],
       [18,  9]])