In [1]:
import numpy as np

## Умножение матриц

In [2]:
X1 = np.array([[1, 2], [3, 4], [5, 6]])
X2 = np.array([[7, 8, 9, 10], [11, 12, 13, 14]])

In [3]:
X1.shape, X2.shape

((3, 2), (2, 4))

In [5]:
Z = np.dot(X1, X2)
Z

array([[ 29,  32,  35,  38],
       [ 65,  72,  79,  86],
       [101, 112, 123, 134]])

In [6]:
Z.shape

(3, 4)

#### Модуль numpy.linalg: возведение матрицы в квадрат

In [10]:
X1 = np.array([[1, 2, 3], [3, 4, 5], [5, 6, 7]])

In [11]:
X1_square = np.dot(X1, X1)
X1_square

array([[22, 28, 34],
       [40, 52, 64],
       [58, 76, 94]])

In [16]:
X1_square = np.linalg.matrix_power(X1, 5)
X1_square

array([[ 46224,  60192,  74160],
       [ 86256, 112320, 138384],
       [126288, 164448, 202608]])

#### Создание единичной матрицы

In [27]:
I = np.eye(3, dtype=int)
I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [28]:
X1 = np.array([[1, 2], [3, 4], [5, 6]])

In [29]:
np.dot(I, X1)

array([[1, 2],
       [3, 4],
       [5, 6]])

#### Транспонирование матриц

In [35]:
X1 = np.array([[1, 2], [3, 4], [5, 6]])

In [34]:
Trans = X1.transpose()
Trans

array([[1, 3, 5],
       [2, 4, 6]])

In [33]:
Trans = X1.T
Trans

array([[1, 3, 5],
       [2, 4, 6]])

#### Вычисление определителя и ранга матрицы

In [41]:
X1 = np.array([[1, 2], [1, 2]])

In [42]:
np.linalg.det(X1)

np.float64(0.0)

In [43]:
np.linalg.matrix_rank(X1)

np.int64(1)

In [44]:
X1 = np.array([[1, 2], [3, 4], [5, 6]])

In [45]:
np.linalg.matrix_rank(X1)

np.int64(2)

#### Вычисление обратной матрицы

In [48]:
X1 = np.array([[1, 2], [3, 4]])

In [50]:
B = np.linalg.inv(X1)
B

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [51]:
np.linalg.inv(B)

array([[1., 2.],
       [3., 4.]])