In [33]:
import numpy as np

In [34]:
a = [i for i in range(10)]
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [35]:
b = np.array(a)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
b = np.array([i for i in range(10)])
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
c = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9)
b = np.array(c)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
type(b)

numpy.ndarray

In [39]:
b = np.array(a, dtype = float)
b

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [40]:
a = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9.9]

In [41]:
b = np.array(a, dtype = int)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
b = np.array(a, dtype = str)
b

array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9.9'], dtype='<U3')

In [43]:
b.dtype

dtype('<U3')

In [44]:
b[0], b[3]

(np.str_('0'), np.str_('3'))

In [45]:
b.ndim, b.shape

(1, (10,))

2D array

In [46]:
b = np.array([[0, 1, 2, 3, 4, 5], [5, 6, 4, 3, 2, 5], [5, 4, 3, 4, 3, 6]])

In [47]:
b

array([[0, 1, 2, 3, 4, 5],
       [5, 6, 4, 3, 2, 5],
       [5, 4, 3, 4, 3, 6]])

In [48]:
b.shape, b.size, b.ndim

((3, 6), 18, 2)

In [49]:
b[1][4]

np.int64(2)

In [50]:
b[1, 4]

np.int64(2)

In [51]:
b[0:2, 0:3]

array([[0, 1, 2],
       [5, 6, 4]])

In [52]:
b[:2, :3]

array([[0, 1, 2],
       [5, 6, 4]])

In [53]:
b[:, 2:]

array([[2, 3, 4, 5],
       [4, 3, 2, 5],
       [3, 4, 3, 6]])

In [54]:
c = b[:, 3:]
c

array([[3, 4, 5],
       [3, 2, 5],
       [4, 3, 6]])

In [55]:
c[1, 1] = 999
b

array([[  0,   1,   2,   3,   4,   5],
       [  5,   6,   4,   3, 999,   5],
       [  5,   4,   3,   4,   3,   6]])

In [56]:
b[2, 5] = 555
c

array([[  3,   4,   5],
       [  3, 999,   5],
       [  4,   3, 555]])

In [57]:
c = b[::, 3:].copy()

In [58]:
c[0, 0] = 777
c

array([[777,   4,   5],
       [  3, 999,   5],
       [  4,   3, 555]])

In [59]:
b

array([[  0,   1,   2,   3,   4,   5],
       [  5,   6,   4,   3, 999,   5],
       [  5,   4,   3,   4,   3, 555]])

Data types

In [60]:
b = np.array([1., 2., 3.], dtype = np.float32)
b

array([1., 2., 3.], dtype=float32)

In [61]:
b = np.array([1., 2., 3.], dtype = np.float64)
b

array([1., 2., 3.])

In [62]:
b = np.array([1., 2., 3.], dtype = np.int32)
b

array([1, 2, 3], dtype=int32)

In [63]:
b = np.array([1., 2., 3.], dtype = np.int64)
b

array([1, 2, 3])