In [3]:
import numpy as np

In [17]:
a = [i for i in range(10)]
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [18]:
b = np.array(a)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
b = np.array([i for i in range(10)])
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
c = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9)
b = np.array(c)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
type(b)

numpy.ndarray

In [23]:
b = np.array(a, dtype = float)
b

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
a = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9.9]

In [24]:
b = np.array(a, dtype = int)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
b = np.array(a, dtype = str)
b

array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U1')

In [27]:
b.dtype

dtype('<U1')

In [29]:
b[0], b[3]

(np.str_('0'), np.str_('3'))

In [30]:
b.ndim, b.shape

(1, (10,))

2D array

In [4]:
b = np.array([[0, 1, 2, 3, 4, 5], [5, 6, 4, 3, 2, 5], [5, 4, 3, 4, 3, 6]])

In [34]:
b

array([[0, 1, 2, 3, 4, 5],
       [5, 6, 4, 3, 2, 5],
       [5, 4, 3, 4, 3, 6]])

In [37]:
b.shape, b.size

((3, 6), 18)

In [39]:
b[1][4]

np.int64(2)

In [41]:
b[1, 4]

np.int64(2)

In [43]:
b[0:2, 0:3]

array([[0, 1, 2],
       [5, 6, 4]])

In [45]:
b[:2, :3]

array([[0, 1, 2],
       [5, 6, 4]])

In [5]:
b[:, 2:]

array([[2, 3, 4, 5],
       [4, 3, 2, 5],
       [3, 4, 3, 6]])

In [6]:
c = b[:, 3:]
c

array([[3, 4, 5],
       [3, 2, 5],
       [4, 3, 6]])

In [55]:
c[1, 1] = 999
b

array([[  0,   1,   2,   3,   4,   5],
       [  5,   6,   4,   3, 999,   5],
       [  5,   4,   3,   4,   3,   6]])

In [57]:
b[2, 5] = 555
c

array([[  3,   4,   5],
       [  3, 999,   5],
       [  4,   3, 555]])

In [59]:
c = b[::, 3:].copy()

In [60]:
c[0, 0] = 777
c

array([[777,   4,   5],
       [  3, 999,   5],
       [  4,   3, 555]])

In [61]:
b

array([[  0,   1,   2,   3,   4,   5],
       [  5,   6,   4,   3, 999,   5],
       [  5,   4,   3,   4,   3, 555]])

Data types

In [63]:
b = np.array([1., 2., 3.], dtype = np.float32)
b

array([1., 2., 3.], dtype=float32)

In [65]:
b = np.array([1., 2., 3.], dtype = np.float64)
b

array([1., 2., 3.])

In [66]:
b = np.array([1., 2., 3.], dtype = np.int32)
b

array([1, 2, 3], dtype=int32)

In [68]:
b = np.array([1., 2., 3.], dtype = np.int64)
b

array([1, 2, 3])